"use client";

import { useState, useEffect } from "react";
import {
    Receipt, Plus, Search, Filter,
    CheckCircle2, XCircle, Clock,
    Download, Eye, MoreVertical,
    Wallet, TrendingUp, CreditCard, PieChart,
    Loader2, Upload, Calendar, DollarSign, Users
} from "lucide-react";
import { format } from "date-fns";
import toast from "react-hot-toast";

export default function ExpenseManager({ employeeId, isAdmin = false, activeClaimType = 'all' }) {
    const [expenses, setExpenses] = useState([]);
    const [loading, setLoading] = useState(true);
    const [showModal, setShowModal] = useState(false);
    const [editData, setEditData] = useState(null);
    const [filterStatus, setFilterStatus] = useState("all");
    const [showFilters, setShowFilters] = useState(false);
    const [searchQuery, setSearchQuery] = useState("");
    const [dateRange, setDateRange] = useState({ start: '', end: '' });
    const [stats, setStats] = useState({
        totalAmount: 0,
        pendingClaims: 0,
        approvedAmount: 0,
        rejectedClaims: 0
    });

    useEffect(() => {
        // Debounce search slightly to avoid too many requests
        const timeoutId = setTimeout(() => {
            fetchExpenses();
        }, 300);
        return () => clearTimeout(timeoutId);
    }, [employeeId, filterStatus, dateRange.start, dateRange.end, searchQuery, activeClaimType]);

    const fetchExpenses = async () => {
        try {
            setLoading(true);
            let url = `/api/v1/admin/finance/expenses`;
            const params = new URLSearchParams();
            if (!isAdmin && employeeId) params.append('employeeId', employeeId);
            if (filterStatus !== "all") params.append('status', filterStatus);
            if (dateRange.start) params.append('startDate', dateRange.start);
            if (dateRange.end) params.append('endDate', dateRange.end);
            if (searchQuery) params.append('search', searchQuery);
            if (activeClaimType !== 'all') params.append('claimType', activeClaimType);

            const res = await fetch(`${url}?${params.toString()}`);
            const data = await res.json();

            const expenseList = data.expenses || [];
            setExpenses(expenseList);

            // Calculate stats
            const s = expenseList.reduce((acc, curr) => {
                acc.totalAmount += curr.amount;
                if (curr.status === 'Pending') acc.pendingClaims++;
                if (curr.status === 'Approved') acc.approvedAmount += curr.amount;
                if (curr.status === 'Rejected') acc.rejectedClaims++;
                return acc;
            }, { totalAmount: 0, pendingClaims: 0, approvedAmount: 0, rejectedClaims: 0 });
            setStats(s);

        } catch (error) {
            toast.error("Failed to load expenses");
        } finally {
            setLoading(false);
        }
    };

    const handleDownloadReceipt = (expense) => {
        // Create a simple receipt text file
        const content = `
RECEIPT / CLAIM VOUCHER
-----------------------
Title: ${expense.title}
Category: ${expense.category}
Date: ${format(new Date(expense.date), 'dd MMM yyyy')}
Amount: Rs. ${expense.amount.toLocaleString()}
Status: ${expense.status}
Employee ID: ${expense.employee || 'N/A'}

Description:
${expense.description || 'No description provided'}

-----------------------
Generated by HR & Payroll System
        `;

        const blob = new Blob([content], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Receipt-${expense.title.replace(/\s+/g, '-')}-${format(new Date(expense.date), 'yyyyMMdd')}.txt`;
        a.click();
        window.URL.revokeObjectURL(url);
        toast.success("Receipt downloaded");
    };

    const handleUpdateStatus = async (id, newStatus) => {
        try {
            const res = await fetch('/api/v1/admin/finance/expenses', {
                method: 'PUT',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ id, status: newStatus })
            });

            if (!res.ok) throw new Error("Failed to update status");

            toast.success(`Expense ${newStatus.toLowerCase()} successfully`);
            fetchExpenses();
        } catch (error) {
            toast.error(error.message);
        }
    };

    const handleDelete = async (id) => {
        if (!confirm("Are you sure you want to delete this expense? This action cannot be undone.")) return;
        
        try {
            const res = await fetch(`/api/v1/admin/finance/expenses?id=${id}`, {
                method: 'DELETE'
            });

            if (!res.ok) throw new Error("Failed to delete expense");

            toast.success("Expense deleted successfully");
            fetchExpenses();
        } catch (error) {
            toast.error(error.message);
        }
    };

    return (
        <div className="space-y-8 animate-in fade-in duration-700">
            {/* Header Section */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    {isAdmin ? (
                        <>
                            <h1 className="text-3xl font-black text-slate-900 tracking-tight">Expense Management</h1>
                            <p className="text-slate-500 text-sm font-medium mt-1">Track spendings, submit reimbursements, and manage approvals.</p>
                        </>
                    ) : (
                        <>
                            <h2 className="text-2xl font-black text-slate-900 tracking-tight">Claim History</h2>
                            <p className="text-slate-500 text-sm font-medium mt-1">View your past claims and file new ones.</p>
                        </>
                    )}
                </div>
                <button
                    onClick={() => {
                        setEditData(null);
                        setShowModal(true);
                    }}
                    className="bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-3 rounded-2xl text-sm font-black shadow-lg shadow-indigo-100 transition-all flex items-center gap-2 group"
                >
                    <Plus className="w-4 h-4 transition-transform group-hover:rotate-90" /> File New Claim
                </button>
            </div>

            {/* Quick Stats */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                <div 
                    onClick={() => setFilterStatus('all')}
                    className={`bg-white p-6 rounded-3xl border shadow-sm relative overflow-hidden group hover:shadow-xl transition-all duration-500 border-l-4 border-l-indigo-500 cursor-pointer ${filterStatus === 'all' ? 'border-indigo-300 ring-2 ring-indigo-500/20' : 'border-slate-200'}`}>
                    <div className="absolute top-0 right-0 w-24 h-24 bg-indigo-50 rounded-full -mr-12 -mt-12 transition-transform group-hover:scale-150 duration-700"></div>
                    <div className="relative z-10">
                        <div className="w-12 h-12 bg-indigo-100 rounded-2xl flex items-center justify-center mb-4">
                            <Wallet className="w-6 h-6 text-indigo-600" />
                        </div>
                        <p className="text-slate-500 text-[10px] font-black uppercase tracking-widest">Total Claimed</p>
                        <h3 className="text-2xl font-black text-slate-900 mt-1">₹{stats.totalAmount.toLocaleString()}</h3>
                    </div>
                </div>

                <div 
                    onClick={() => setFilterStatus('Pending')}
                    className={`bg-white p-6 rounded-3xl border shadow-sm relative overflow-hidden group hover:shadow-xl transition-all duration-500 border-l-4 border-l-orange-500 cursor-pointer ${filterStatus === 'Pending' ? 'border-orange-300 ring-2 ring-orange-500/20' : 'border-slate-200'}`}>
                    <div className="absolute top-0 right-0 w-24 h-24 bg-orange-50 rounded-full -mr-12 -mt-12 transition-transform group-hover:scale-150 duration-700"></div>
                    <div className="relative z-10">
                        <div className="w-12 h-12 bg-orange-100 rounded-2xl flex items-center justify-center mb-4">
                            <Clock className="w-6 h-6 text-orange-600" />
                        </div>
                        <p className="text-slate-500 text-[10px] font-black uppercase tracking-widest">Pending Claims</p>
                        <h3 className="text-2xl font-black text-slate-900 mt-1">{stats.pendingClaims}</h3>
                    </div>
                </div>

                <div 
                    onClick={() => setFilterStatus('Approved')}
                    className={`bg-white p-6 rounded-3xl border shadow-sm relative overflow-hidden group hover:shadow-xl transition-all duration-500 border-l-4 border-l-emerald-500 cursor-pointer ${filterStatus === 'Approved' ? 'border-emerald-300 ring-2 ring-emerald-500/20' : 'border-slate-200'}`}>
                    <div className="absolute top-0 right-0 w-24 h-24 bg-emerald-50 rounded-full -mr-12 -mt-12 transition-transform group-hover:scale-150 duration-700"></div>
                    <div className="relative z-10">
                        <div className="w-12 h-12 bg-emerald-100 rounded-2xl flex items-center justify-center mb-4">
                            <CheckCircle2 className="w-6 h-6 text-emerald-600" />
                        </div>
                        <p className="text-slate-500 text-[10px] font-black uppercase tracking-widest">Approved Amount</p>
                        <h3 className="text-2xl font-black text-slate-900 mt-1">₹{stats.approvedAmount.toLocaleString()}</h3>
                    </div>
                </div>

                <div 
                    onClick={() => setFilterStatus('Rejected')}
                    className={`bg-white p-6 rounded-3xl border shadow-sm relative overflow-hidden group hover:shadow-xl transition-all duration-500 border-l-4 border-l-rose-500 cursor-pointer ${filterStatus === 'Rejected' ? 'border-rose-300 ring-2 ring-rose-500/20' : 'border-slate-200'}`}>
                    <div className="absolute top-0 right-0 w-24 h-24 bg-rose-50 rounded-full -mr-12 -mt-12 transition-transform group-hover:scale-150 duration-700"></div>
                    <div className="relative z-10">
                        <div className="w-12 h-12 bg-rose-100 rounded-2xl flex items-center justify-center mb-4">
                            <XCircle className="w-6 h-6 text-rose-600" />
                        </div>
                        <p className="text-slate-500 text-[10px] font-black uppercase tracking-widest">Rejected</p>
                        <h3 className="text-2xl font-black text-slate-900 mt-1">{stats.rejectedClaims}</h3>
                    </div>
                </div>
            </div>

            {/* Main Content */}
            <div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden">
                <div className="p-6 border-b border-slate-100 flex flex-col md:flex-row gap-4 justify-between bg-slate-50/50">
                    <div className="relative w-full md:w-96">
                        <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-slate-400" />
                        <input
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            placeholder="Search by title or category..."
                            className="w-full pl-10 pr-4 py-2.5 bg-white border border-slate-200 rounded-xl text-sm outline-none focus:ring-4 focus:ring-indigo-500/10 transition-all"
                        />
                    </div>
                    <div className="flex gap-2">
                        <select
                            value={filterStatus}
                            onChange={(e) => setFilterStatus(e.target.value)}
                            className="bg-white border border-slate-200 rounded-xl px-4 py-2 text-xs font-bold text-slate-600 outline-none hover:bg-slate-50 transition-all"
                        >
                            <option value="all">All Status</option>
                            <option value="Pending">Pending</option>
                            <option value="Approved">Approved</option>
                            <option value="Rejected">Rejected</option>
                            <option value="Paid">Paid</option>
                        </select>
                        <button
                            onClick={() => setShowFilters(!showFilters)}
                            className={`p-2.5 border rounded-xl transition-all shadow-sm ${showFilters ? 'bg-indigo-50 border-indigo-200 text-indigo-600' : 'bg-white border-slate-200 text-slate-500 hover:bg-slate-50'}`}
                        >
                            <Filter className="w-4 h-4" />
                        </button>
                    </div>
                </div>

                {/* Advanced Filters */}
                {showFilters && (
                    <div className="p-4 border-b border-slate-100 bg-slate-50/30 flex gap-4 animate-in slide-in-from-top-2">
                        <div>
                            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Start Date</label>
                            <input
                                type="date"
                                value={dateRange.start}
                                onChange={(e) => setDateRange({ ...dateRange, start: e.target.value })}
                                className="px-3 py-2 bg-white border border-slate-200 rounded-lg text-xs font-bold outline-none focus:ring-2 focus:ring-indigo-500/10"
                            />
                        </div>
                        <div>
                            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">End Date</label>
                            <input
                                type="date"
                                value={dateRange.end}
                                onChange={(e) => setDateRange({ ...dateRange, end: e.target.value })}
                                className="px-3 py-2 bg-white border border-slate-200 rounded-lg text-xs font-bold outline-none focus:ring-2 focus:ring-indigo-500/10"
                            />
                        </div>
                    </div>
                )}

                <div className="overflow-x-auto">
                    <table className="w-full">
                        <thead>
                            <tr className="text-left bg-slate-50/30">
                                <th className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">Detail</th>
                                <th className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">Category</th>
                                <th className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest text-center">Date</th>
                                <th className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest text-right">Amount</th>
                                <th className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest text-center">Status</th>
                                <th className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest text-center">Payment</th>
                                <th className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-50">
                            {loading ? (
                                <tr>
                                    <td colSpan="6" className="py-20 text-center">
                                        <Loader2 className="w-8 h-8 text-indigo-600 animate-spin mx-auto mb-2" />
                                        <p className="text-slate-400 text-xs font-bold">Fetching expense records...</p>
                                    </td>
                                </tr>
                            ) : expenses.length === 0 ? (
                                <tr>
                                    <td colSpan="6" className="py-20 text-center">
                                        <Receipt className="w-12 h-12 text-slate-200 mx-auto mb-4" />
                                        <p className="text-slate-500 font-bold">No expenses found.</p>
                                        <p className="text-slate-400 text-xs mt-1">Submit your first claim to get started.</p>
                                    </td>
                                </tr>
                            ) : (
                                expenses.map((expense) => (
                                    <tr key={expense._id} className="group hover:bg-slate-50/50 transition-colors">
                                        <td className="px-6 py-4">
                                            <div>
                                                <div className="flex items-center gap-2">
                                                    <p className="text-sm font-black text-slate-900 line-clamp-1">{expense.title}</p>
                                                    {expense.claimType === 'Team' && (
                                                        <span className="px-1.5 py-0.5 bg-purple-50 text-purple-600 rounded text-[8px] font-black uppercase tracking-widest border border-purple-100">Team</span>
                                                    )}
                                                    {!isAdmin && expense.status === 'Draft' && (
                                                        <span className="px-1.5 py-0.5 bg-indigo-50 text-indigo-600 rounded text-[8px] font-black uppercase tracking-widest border border-indigo-100 animate-pulse">Admin Request</span>
                                                    )}
                                                </div>
                                                <p className="text-[10px] text-slate-400 font-medium">{isAdmin && expense.employee?.personalDetails?.name}</p>
                                            </div>
                                        </td>
                                        <td className="px-6 py-4">
                                            <span className="px-3 py-1 bg-slate-100 rounded-lg text-[10px] font-black text-slate-600 uppercase">
                                                {expense.category}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-center">
                                            <p className="text-xs font-bold text-slate-600">{format(new Date(expense.date), 'MMM dd, yyyy')}</p>
                                        </td>
                                        <td className="px-6 py-4 text-right">
                                            <p className="text-lg font-black text-indigo-600">₹{(expense.amount || 0).toLocaleString()}</p>
                                        </td>
                                        <td className="px-6 py-4 text-center">
                                            <span className={`px-3 py-1 rounded-lg text-[10px] font-black uppercase inline-flex items-center gap-1.5 ${(expense.status === 'Approved' || expense.status === 'Paid') ? 'bg-emerald-50 text-emerald-600' :
                                                expense.status === 'Pending' ? 'bg-orange-50 text-orange-600' :
                                                    expense.status === 'Rejected' ? 'bg-rose-50 text-rose-600' :
                                                        'bg-indigo-50 text-indigo-600'
                                                }`}>
                                                {(expense.status === 'Approved' || expense.status === 'Paid') && <CheckCircle2 className="w-3 h-3" />}
                                                {expense.status === 'Pending' && <Clock className="w-3 h-3" />}
                                                {expense.status === 'Rejected' && <XCircle className="w-3 h-3" />}
                                                {(expense.status === 'Approved' || expense.status === 'Paid') ? 'Approved' : expense.status}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-center">
                                            <span className={`px-3 py-1 rounded-lg text-[10px] font-black uppercase inline-flex items-center gap-1.5 ${expense.status === 'Paid' ? 'bg-emerald-50 text-emerald-600' :
                                                expense.status === 'Rejected' ? 'bg-rose-50 text-rose-600' :
                                                    'bg-orange-50 text-orange-600'
                                                }`}>
                                                {expense.status === 'Paid' && <CheckCircle2 className="w-3 h-3" />}
                                                {expense.status === 'Rejected' && <XCircle className="w-3 h-3" />}
                                                {(expense.status !== 'Paid' && expense.status !== 'Rejected') && <Clock className="w-3 h-3" />}
                                                {expense.status === 'Paid' ? 'Done' : expense.status === 'Rejected' ? 'Rejected' : 'Pending'}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-right">
                                            <div className="flex justify-end gap-2 outline-none">
                                                {(expense.status === 'Pending' || (!isAdmin && expense.status === 'Draft')) && (
                                                    <>
                                                        <button
                                                            onClick={() => { setEditData(expense); setShowModal(true); }}
                                                            className={`p-2 rounded-xl transition-all ${expense.status === 'Draft' ? 'bg-indigo-50 text-indigo-600 px-3 flex items-center gap-2' : 'hover:bg-orange-50 text-slate-400 hover:text-orange-600'}`}
                                                            title={expense.status === 'Draft' ? "Complete Claim" : "Edit Expense"}
                                                        >
                                                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" /></svg>
                                                            {expense.status === 'Draft' && <span className="text-[9px] font-black uppercase">Complete</span>}
                                                        </button>
                                                        <button
                                                            onClick={() => handleDelete(expense._id)}
                                                            className="p-2 hover:bg-rose-50 rounded-xl text-slate-400 hover:text-rose-600 transition-all"
                                                            title="Delete Expense"
                                                        >
                                                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg>
                                                        </button>
                                                    </>
                                                )}
                                                <button
                                                    onClick={() => handleDownloadReceipt(expense)}
                                                    className="p-2 hover:bg-indigo-50 rounded-xl text-slate-400 hover:text-indigo-600 transition-all"
                                                    title="Download Receipt"
                                                >
                                                    <Download className="w-4 h-4" />
                                                </button>
                                                {isAdmin && expense.status === 'Pending' && (
                                                    <div className="flex gap-2">
                                                        <button
                                                            onClick={() => handleUpdateStatus(expense._id, 'Approved')}
                                                            className="p-2 bg-emerald-50 text-emerald-600 rounded-xl hover:bg-emerald-100 transition-all font-black text-[10px] uppercase px-3"
                                                        >
                                                            Approve
                                                        </button>
                                                        <button
                                                            onClick={() => handleUpdateStatus(expense._id, 'Rejected')}
                                                            className="p-2 bg-rose-50 text-rose-600 rounded-xl hover:bg-rose-100 transition-all font-black text-[10px] uppercase px-3"
                                                        >
                                                            Reject
                                                        </button>
                                                    </div>
                                                )}
                                                {!isAdmin && expense.status === 'Draft' && (
                                                    <button className="p-2 hover:bg-indigo-50 rounded-xl text-slate-400 hover:text-indigo-600 transition-all">
                                                        <Eye className="w-4 h-4" />
                                                    </button>
                                                )}
                                            </div>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Modal for new/edit Expense */}
            {showModal && (
                <ExpenseFormModal
                    employeeId={employeeId}
                    isAdmin={isAdmin}
                    editData={editData}
                    defaultClaimType={activeClaimType !== 'all' ? activeClaimType : 'Personal'}
                    onClose={() => {
                        setShowModal(false);
                        setEditData(null);
                    }}
                    onSuccess={() => {
                        setShowModal(false);
                        setEditData(null);
                        fetchExpenses();
                    }}
                />
            )}
        </div>
    );
}

export function ExpenseFormModal({ employeeId, editData, isAdmin = false, defaultClaimType = 'Personal', onClose, onSuccess }) {
    const [submitting, setSubmitting] = useState(false);
    const [employees, setEmployees] = useState([]);
    const [departments, setDepartments] = useState([]);
    const [teams, setTeams] = useState([]);
    const [searchEmployee, setSearchEmployee] = useState("");
    const [formData, setFormData] = useState({
        employee: editData ? editData.employee?._id || editData.employee : (employeeId || ''),
        title: editData?.title || '',
        category: editData?.category || 'Food',
        amount: editData?.amount || '',
        maxAmount: editData?.maxAmount || 0,
        date: editData?.date ? format(new Date(editData.date), 'yyyy-MM-dd') : format(new Date(), 'yyyy-MM-dd'),
        description: editData?.description || '',
        claimType: editData?.claimType || defaultClaimType,
        teamMembers: editData?.teamMembers || '',
        status: editData?.status || (isAdmin && !editData ? 'Draft' : 'Pending'),
        gstDetails: {
            gstNumber: '',
            gstAmount: 0,
            isGstIncluded: true
        }
    });

    useEffect(() => {
        if (isAdmin) {
            fetchInitialData();
        }
    }, [isAdmin]);

    const fetchInitialData = async () => {
        try {
            const [empRes, deptRes, teamRes] = await Promise.all([
                fetch('/api/v1/admin/employees?limit=100'),
                fetch('/api/v1/admin/crm/departments'),
                fetch('/api/v1/admin/crm/teams')
            ]);
            
            const [empData, deptData, teamData] = await Promise.all([
                empRes.json(),
                deptRes.json(),
                teamRes.json()
            ]);

            setEmployees(empData.data || []);
            setDepartments(deptData.data || []);
            setTeams(teamData.data || []);
        } catch (error) {
            console.error("Failed to fetch initiation data", error);
        }
    };

    const filteredEmployees = employees.filter(emp => {
        const name = emp.personalDetails?.name || `${emp.personalDetails?.firstName} ${emp.personalDetails?.lastName}`;
        const id = emp.employeeId || "";
        const query = searchEmployee.toLowerCase();
        return name.toLowerCase().includes(query) || id.toLowerCase().includes(query);
    });

    const filteredItems = (formData.claimType === 'Department' 
        ? departments.map(d => d.departmentName)
        : teams.map(t => t.name)
    ).filter(item => 
        item.toLowerCase().includes(searchEmployee.toLowerCase())
    );

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            setSubmitting(true);
            // If an employee is submitting a draft, change status to Pending
            const finalStatus = (!isAdmin && formData.status === 'Draft') ? 'Pending' : formData.status;
            
            const payload = { ...formData, status: finalStatus };
            if (editData) payload.id = editData._id;

            // Clean up payload: convert empty strings to null for ObjectIds
            ['employee', 'costCenter', 'approvedBy'].forEach(field => {
                if (payload[field] === '') payload[field] = null;
            });

            const url = editData 
                ? `/api/v1/admin/finance/expenses?id=${editData._id}` 
                : '/api/v1/admin/finance/expenses';

            const res = await fetch(url, {
                method: editData ? 'PUT' : 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });

            if (!res.ok) {
                const errData = await res.json();
                const errorMsg = Array.isArray(errData.error) ? errData.error[0]?.message : errData.error;
                throw new Error(errorMsg || `Failed to ${editData ? 'update' : 'submit'} claim`);
            }

            const successMsg = isAdmin && !editData 
                ? "Expense claim initiated successfully! Employees will be notified."
                : `Expense claim ${editData ? 'updated' : 'submitted'} successfully!`;

            toast.success(successMsg);
            onSuccess();
        } catch (error) {
            toast.error(error.message);
        } finally {
            setSubmitting(false);
        }
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-500">
            <div className="bg-white rounded-[2.5rem] w-full max-w-xl shadow-2xl border border-slate-200 overflow-hidden scale-in duration-300">
                <div className="p-8 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
                    <div>
                        <h2 className="text-2xl font-black text-slate-900 tracking-tight">{editData ? 'Edit Expense Claim' : 'File Expense Claim'}</h2>
                        <p className="text-slate-400 text-xs font-bold mt-1 uppercase tracking-widest">{editData ? 'Update your pending claim details' : 'Draft your reimbursement request'}</p>
                    </div>
                </div>

                <form onSubmit={handleSubmit} className="p-8 space-y-6 max-h-[70vh] overflow-y-auto">
                    {!isAdmin && editData?.status === 'Draft' && (
                        <div className="bg-indigo-50 border border-indigo-100 rounded-2xl p-4 mb-6">
                            <div className="flex gap-3">
                                <div className="w-10 h-10 bg-white rounded-xl flex items-center justify-center shadow-sm">
                                    <Receipt className="w-5 h-5 text-indigo-600" />
                                </div>
                                <div>
                                    <p className="text-sm font-black text-slate-900">Admin Request</p>
                                    <p className="text-xs text-slate-500 font-medium leading-relaxed">Admin has requested you to file this expense. Please review the details below, enter the final amount, and upload your receipt to submit for approval.</p>
                                </div>
                            </div>
                        </div>
                    )}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {/* Admin Specific: Employee/Team Selection */}
                        {isAdmin && !editData && (
                            <div className="md:col-span-2">
                                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-2">Select Recipient (Employee or Team) *</label>
                                <div className="flex gap-2 mb-6">
                                    {[
                                        { id: 'Personal', label: 'Individual', icon: Users },
                                        { id: 'Department', label: 'Department', icon: PieChart },
                                        { id: 'Team', label: 'Team', icon: TrendingUp }
                                    ].map(type => (
                                        <button
                                            key={type.id}
                                            type="button"
                                            onClick={() => {
                                                setFormData({ ...formData, claimType: type.id });
                                                setSearchEmployee("");
                                            }}
                                            className={`flex-1 py-3 px-2 rounded-xl text-[9px] font-black uppercase tracking-widest border-2 transition-all flex items-center justify-center gap-1.5 ${
                                                formData.claimType === type.id 
                                                ? 'bg-indigo-600 border-indigo-600 text-white shadow-xl shadow-indigo-100' 
                                                : 'bg-white border-slate-100 text-slate-400 hover:border-slate-200'
                                            }`}
                                        >
                                            <type.icon className="w-3.5 h-3.5" />
                                            {type.label}
                                        </button>
                                    ))}
                                </div>

                                {formData.claimType === 'Personal' ? (
                                    <div className="space-y-4">
                                        <div className="relative">
                                            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                                            <input 
                                                type="text"
                                                placeholder="Search by name or ID..."
                                                value={searchEmployee}
                                                onChange={e => setSearchEmployee(e.target.value)}
                                                className="w-full pl-11 pr-4 py-4 bg-slate-50 border border-slate-200 rounded-2xl text-sm font-bold outline-none focus:ring-4 focus:ring-indigo-500/10 transition-all"
                                            />
                                        </div>
                                        <div className="max-h-48 overflow-y-auto border border-slate-100 rounded-2xl p-2 bg-slate-50/50 scrollbar-hide">
                                            {filteredEmployees.length === 0 ? (
                                                <div className="p-4 text-center text-slate-400 text-xs font-bold uppercase tracking-widest italic">No employees found</div>
                                            ) : (
                                                filteredEmployees.map(emp => (
                                                    <div 
                                                        key={emp._id}
                                                        onClick={() => setFormData({ ...formData, employee: emp._id })}
                                                        className={`flex items-center justify-between p-3 rounded-xl cursor-pointer transition-all mb-1 ${
                                                            formData.employee === emp._id 
                                                            ? 'bg-white shadow-md border-l-4 border-l-indigo-600' 
                                                            : 'hover:bg-white hover:shadow-sm'
                                                        }`}
                                                    >
                                                        <div className="flex items-center gap-3">
                                                            <div className="w-8 h-8 bg-indigo-50 rounded-lg flex items-center justify-center text-indigo-600 font-black text-[10px]">
                                                                {emp.personalDetails?.firstName?.charAt(0)}{emp.personalDetails?.lastName?.charAt(0)}
                                                            </div>
                                                            <div>
                                                                <p className="text-sm font-black text-slate-900">{emp.personalDetails?.firstName} {emp.personalDetails?.lastName}</p>
                                                                <div className="flex items-center gap-2 mt-0.5">
                                                                    <p className="text-[10px] text-indigo-600 font-black uppercase tracking-widest bg-indigo-50 px-1 rounded">{emp.employeeId}</p>
                                                                    <p className="text-[10px] text-slate-400 font-bold italic">{emp.personalDetails?.email}</p>
                                                                    {emp.jobDetails?.department && (
                                                                        <p className="text-[10px] text-slate-400 font-bold">• {emp.jobDetails.department}</p>
                                                                    )}
                                                                </div>
                                                            </div>
                                                        </div>
                                                        {formData.employee === emp._id && <CheckCircle2 className="w-4 h-4 text-indigo-600" />}
                                                    </div>
                                                ))
                                            )}
                                        </div>
                                    </div>
                                ) : (
                                    <div className="space-y-4">
                                        <div className="relative">
                                            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                                            <input 
                                                type="text"
                                                placeholder={`Search by ${formData.claimType}...`}
                                                value={formData.teamMembers}
                                                onChange={e => {
                                                    setFormData({ ...formData, teamMembers: e.target.value });
                                                    setSearchEmployee(e.target.value);
                                                }}
                                                className="w-full pl-11 pr-4 py-4 bg-slate-50 border border-slate-200 rounded-2xl text-sm font-bold outline-none focus:ring-4 focus:ring-indigo-500/10 transition-all"
                                            />
                                        </div>
                                        <div className="max-h-48 overflow-y-auto border border-slate-100 rounded-2xl p-2 bg-slate-50/50 scrollbar-hide">
                                            {filteredItems.length === 0 ? (
                                                <div className="p-4 text-center text-slate-400 text-xs font-bold uppercase tracking-widest italic">No matching {formData.claimType.toLowerCase()}s found. Type to add custom.</div>
                                            ) : (
                                                filteredItems.map(item => (
                                                    <div 
                                                        key={item}
                                                        onClick={() => setFormData({ ...formData, teamMembers: item })}
                                                        className={`flex items-center justify-between p-3 rounded-xl cursor-pointer transition-all mb-1 ${
                                                            formData.teamMembers === item 
                                                            ? 'bg-white shadow-md border-l-4 border-l-indigo-600' 
                                                            : 'hover:bg-white hover:shadow-sm'
                                                        }`}
                                                    >
                                                        <div className="flex items-center gap-3">
                                                            <div className={`w-8 h-8 rounded-lg flex items-center justify-center font-black text-[10px] ${formData.claimType === 'Department' ? 'bg-orange-50 text-orange-600' : 'bg-emerald-50 text-emerald-600'}`}>
                                                                {formData.claimType === 'Department' ? <PieChart className="w-4 h-4" /> : <TrendingUp className="w-4 h-4" />}
                                                            </div>
                                                            <div>
                                                                <p className="text-sm font-black text-slate-900">{item}</p>
                                                                <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">{formData.claimType}</p>
                                                            </div>
                                                        </div>
                                                        {formData.teamMembers === item && <CheckCircle2 className="w-4 h-4 text-indigo-600" />}
                                                    </div>
                                                ))
                                            )}
                                        </div>
                                        <p className="text-[10px] text-slate-400 font-medium italic">* This will be assigned to all members of the selected {formData.claimType.toLowerCase()}.</p>
                                    </div>
                                )}
                            </div>
                        )}

                        <div className="md:col-span-2">
                            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-2">Claim Title / Purpose *</label>
                            <input
                                required
                                value={formData.title}
                                onChange={e => setFormData({ ...formData, title: e.target.value })}
                                className="w-full p-4 bg-slate-50 border border-slate-200 rounded-2xl text-sm outline-none focus:ring-4 focus:ring-indigo-500/10 font-bold"
                                placeholder="e.g., Client Dinner, Office Stationery"
                            />
                        </div>

                        <div>
                            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-2">Category</label>
                            <select
                                value={formData.category}
                                onChange={e => setFormData({ ...formData, category: e.target.value })}
                                className="w-full p-4 bg-slate-50 border border-slate-200 rounded-2xl text-sm outline-none font-bold"
                            >
                                <option>Food</option>
                                <option>Travel</option>
                                <option>Accommodation</option>
                                <option>Equipment</option>
                                <option>Software</option>
                                <option>Utilities</option>
                                <option>Other</option>
                            </select>
                        </div>

                        {/* Admin Initiation: Show Max Amount field */}
                        {(isAdmin && !editData) && (
                            <div className="md:col-span-2 p-4 bg-indigo-50 border border-indigo-100 rounded-2xl">
                                <label className="text-[10px] font-black text-indigo-400 uppercase tracking-widest block mb-2">Set Maximum Allowed Amount (Optional)</label>
                                <div className="relative">
                                    <DollarSign className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-indigo-400" />
                                    <input
                                        type="number"
                                        value={formData.maxAmount || ''}
                                        onChange={e => {
                                            const val = e.target.value === '' ? 0 : parseFloat(e.target.value);
                                            setFormData({ ...formData, maxAmount: isNaN(val) ? 0 : val });
                                        }}
                                        className="w-full pl-10 pr-4 py-4 bg-white border border-indigo-200 rounded-2xl text-sm outline-none focus:ring-4 focus:ring-indigo-500/10 font-black text-indigo-900"
                                        placeholder="No limit (0.00)"
                                    />
                                </div>
                                <p className="text-[10px] text-indigo-400 font-medium mt-2 italic">* Employees will be restricted or warned if they exceed this amount.</p>
                            </div>
                        )}

                        {/* Only show amount and receipts if it's NOT an admin initiation OR if it's an employee filling the draft */}
                        {(!isAdmin || editData) && (
                            <>
                                <div>
                                    <div className="flex justify-between items-center mb-2">
                                        <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block">Amount (₹)</label>
                                        {formData.maxAmount > 0 && (
                                            <span className="text-[10px] font-black text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded">Limit: ₹{formData.maxAmount}</span>
                                        )}
                                    </div>
                                    <div className="relative">
                                        <DollarSign className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                                        <input
                                            type="number"
                                            required={formData.status !== 'Draft'}
                                            value={formData.amount || ''}
                                            onChange={e => {
                                                const val = e.target.value === '' ? 0 : parseFloat(e.target.value);
                                                setFormData({ ...formData, amount: isNaN(val) ? 0 : val });
                                            }}
                                            className={`w-full pl-10 pr-4 py-4 bg-slate-50 border rounded-2xl text-sm outline-none focus:ring-4 focus:ring-indigo-500/10 font-black ${
                                                formData.maxAmount > 0 && formData.amount > formData.maxAmount 
                                                ? 'border-rose-300 ring-4 ring-rose-500/10 text-rose-600' 
                                                : 'border-slate-200 text-slate-900'
                                            }`}
                                            placeholder="0.00"
                                        />
                                    </div>
                                    {formData.maxAmount > 0 && formData.amount > formData.maxAmount && (
                                        <p className="text-[10px] text-rose-500 font-black uppercase mt-1 tracking-tighter animate-pulse">Warning: Amount exceeds Admin limit of ₹{formData.maxAmount}!</p>
                                    )}
                                </div>

                                <div>
                                    <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-2">Date</label>
                                    <div className="relative">
                                        <Calendar className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                                        <input
                                            type="date"
                                            required={formData.status !== 'Draft'}
                                            value={formData.date}
                                            onChange={e => setFormData({ ...formData, date: e.target.value })}
                                            className="w-full pl-10 pr-4 py-4 bg-slate-50 border border-slate-200 rounded-2xl text-sm outline-none font-bold"
                                        />
                                    </div>
                                </div>

                                <div className="flex items-center justify-center p-4 border-2 border-dashed border-slate-200 rounded-2xl group hover:border-indigo-400 transition-all cursor-pointer">
                                    <div className="text-center">
                                        <Upload className="w-6 h-6 text-slate-400 mx-auto mb-2 group-hover:text-indigo-600 transition-all" />
                                        <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest group-hover:text-indigo-600 transition-all">Upload Receipt</span>
                                    </div>
                                </div>
                            </>
                        )}

                        <div className="md:col-span-2">
                            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-2">Description / Special Instructions</label>
                            <textarea
                                rows={3}
                                value={formData.description}
                                onChange={e => setFormData({ ...formData, description: e.target.value })}
                                className="w-full p-4 bg-slate-50 border border-slate-200 rounded-2xl text-sm outline-none focus:ring-4 focus:ring-indigo-500/10 font-bold"
                                placeholder={isAdmin ? "Add any notes for the employee..." : "Provide context about this expense..."}
                            />
                        </div>
                    </div>
                </form>

                    <div className="p-8 bg-slate-50 border-t border-slate-100 flex gap-4">
                        <button
                            type="button"
                            onClick={onClose}
                            className="flex-1 py-4 border border-slate-200 rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-white transition-all shadow-sm"
                        >
                            Cancel
                        </button>
                        <button
                            onClick={handleSubmit}
                            disabled={submitting}
                            className="flex-1 py-4 bg-indigo-600 text-white rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-100 flex items-center justify-center gap-2"
                        >
                                {submitting ? <Loader2 className="w-4 h-4 animate-spin" /> : editData ? (formData.status === 'Draft' && !isAdmin ? "Submit for Approval" : "Save Changes") : isAdmin ? "Send to Employee" : "Submit Claim"}
                        </button>
                    </div>
            </div>
        </div>
    );
}
